In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('customer_behavior_2.csv')

In [3]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,37,Male,0
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,37,Male,0
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0.0,James Grant,49,Female,1

In [4]:
df.shape

(250000, 13)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB

In [6]:
df['Customer ID']=df['Customer ID'].astype('object')

In [7]:
df['Purchase Date']=pd.to_datetime(df['Purchase Date'])

In [8]:
df['Purchase Date'].dtype

dtype('<M8[ns]')

In [9]:
df.dtypes

Customer ID                      object
Purchase Date            datetime64[ns]
Product Category                 object
Product Price                     int64
Quantity                          int64
Total Purchase Amount             int64
Payment Method                   object
Customer Age                      int64
Returns                         float64
Customer Name                    object
Age                               int64
Gender                           object
Churn                             int64
dtype: object

In [10]:
(df['Customer Age'] != df['Age']).sum()

np.int64(0)

In [11]:
df=df.drop(columns={'Age'})

In [12]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,Male,0
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,Male,0
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,Male,0
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0.0,James Grant,Female,1

In [13]:
df['Customer Age'].value_counts().head()

Customer Age
58    5009
18    5003
51    4999
70    4989
21    4989
Name: count, dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  object
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Gender                 250000 non-null  object
 11  Churn                  250000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(5)
memory usage: 22.9+ MB

In [15]:
df.describe()

,Purchase Date,Product Price,Quantity,Total Purchase Amount,Customer Age,Returns,Churn
count,250000,250000.000000,250000.000000,250000.000000,250000.000000,202404.000000,250000.000000
mean,2021-11-06 23:31:24.372304384,254.659512,2.998896,2725.370732,43.940528,0.497861,0.199496
min,2020-01-01 00:15:00,10.000000,1.000000,100.000000,18.000000,0.000000,0.000000
25%,2020-12-02 19:33:23.249999872,132.000000,2.000000,1477.000000,31.000000,0.000000,0.000000
50%,2021-11-06 13:10:59,255.000000,3.000000,2724.000000,44.000000,0.000000,0.000000
75%,2022-10-11 03:42:32.750000128,377.000000,4.000000,3974.000000,57.000000,1.000000,0.000000
max,2023-09-15 12:24:08,500.000000,5.000000,5350.000000,70.000000,1.000000,1.000000
std,NaN,141.568577,1.414694,1442.933565,15.350246,0.499997,0.399622

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  object
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Gender                 250000 non-null  object
 11  Churn                  250000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(5)
memory usage: 22.9+ MB

In [17]:
df['Product Category'].unique()

array(['Electronics', 'Home', 'Clothing', 'Books'], dtype=object)

In [18]:
df['Payment Method'].unique()

array(['Credit Card', 'PayPal', 'Cash', 'Crypto'], dtype=object)

In [19]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [20]:
df.isnull().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47596
Customer Name                0
Gender                       0
Churn                        0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  object
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Gender                 250000 non-null  object
 11  Churn                  250000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(5)
memory usage: 22.9+ MB

In [22]:
(df['Product Price']<0).sum()

np.int64(0)

In [23]:
(df['Quantity']<0).sum()

np.int64(0)

In [24]:
(df['Total Purchase Amount']<0).sum()

np.int64(0)

In [25]:
(df['Customer Age']<0).sum()

np.int64(0)

In [26]:
df['Returns'].unique()

array([ 0.,  1., nan])

In [27]:
df['Returns']=df['Returns'].astype('Int64')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  object
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  Int64
 9   Customer Name          250000 non-null  object
 10  Gender                 250000 non-null  object
 11  Churn                  250000 non-null  int64
dtypes: Int64(1), datetime64[ns](1), int64(5), object(5)
memory usage: 23.1+ MB

In [29]:
df['Returns'].fillna(0).astype(int)

0         0
1         0
2         0
3         0
4         0
         ..
249995    1
249996    1
249997    0
249998    0
249999    1
Name: Returns, Length: 250000, dtype: int64

In [30]:
df['Returns'].unique()

<IntegerArray>
[0, 1, <NA>]
Length: 3, dtype: Int64

In [31]:
df.isnull().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47596
Customer Name                0
Gender                       0
Churn                        0
dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  object
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  Int64
 9   Customer Name          250000 non-null  object
 10  Gender                 250000 non-null  object
 11  Churn                  250000 non-null  int64
dtypes: Int64(1), datetime64[ns](1), int64(5), object(5)
memory usage: 23.1+ MB

In [33]:
df['Returns']=df['Returns'].fillna(0)

In [34]:
df['Returns'].unique()

<IntegerArray>
[0, 1]
Length: 2, dtype: Int64

In [35]:
df.isnull().sum()

Customer ID              0
Purchase Date            0
Product Category         0
Product Price            0
Quantity                 0
Total Purchase Amount    0
Payment Method           0
Customer Age             0
Returns                  0
Customer Name            0
Gender                   0
Churn                    0
dtype: int64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  object
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                250000 non-null  Int64
 9   Customer Name          250000 non-null  object
 10  Gender                 250000 non-null  object
 11  Churn                  250000 non-null  int64
dtypes: Int64(1), datetime64[ns](1), int64(5), object(5)
memory usage: 23.1+ MB

In [37]:
df['Returns']=df['Returns'].astype(int)

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df['Churn'].unique()

array([0, 1])

In [40]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0,Christine Hernandez,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0,Christine Hernandez,Male,0
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0,Christine Hernandez,Male,0
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0,Christine Hernandez,Male,0
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0,James Grant,Female,1

In [41]:
import numpy as np

In [42]:
conditions =[
    df['Customer Age'].between(18,25),
    df['Customer Age'].between(26,35),
    df['Customer Age'].between(36,50),
    df['Customer Age']>50
]

choices = ['Young Adult','Adult','Middle Age','Senior']

df['Age Category']=np.select(conditions,choices,default='Unknown')

In [43]:
df[['Customer Age','Age Category']].head(25)

    Customer Age Age Category
0             37   Middle Age
1             37   Middle Age
2             37   Middle Age
3             37   Middle Age
4             49   Middle Age
5             49   Middle Age
6             49   Middle Age
7             49   Middle Age
8             49   Middle Age
9             19  Young Adult
10            19  Young Adult
11            19  Young Adult
12            19  Young Adult
13            19  Young Adult
14            19  Young Adult
15            55       Senior
16            55       Senior
17            55       Senior
18            55       Senior
19            55       Senior
20            67       Senior
21            67       Senior
22            67       Senior
23            67       Senior
24            67       Senior

In [44]:
df['Age Category'].isnull().sum()

np.int64(0)

In [45]:
(df['Customer Age']<18).sum()

np.int64(0)

In [46]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Gender,Churn,Age Category
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0,Christine Hernandez,Male,0,Middle Age
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0,Christine Hernandez,Male,0,Middle Age
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0,Christine Hernandez,Male,0,Middle Age
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0,Christine Hernandez,Male,0,Middle Age
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0,James Grant,Female,1,Middle Age

In [47]:
(df['Total Purchase Amount'] != df['Product Price'] * df['Quantity']).sum()

np.int64(249952)

In [48]:
df['check total'] = df['Product Price'] * df['Quantity']

In [49]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Gender,Churn,Age Category,check total
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0,Christine Hernandez,Male,0,Middle Age,36
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,1872
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,576
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,196
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0,James Grant,Female,1,Middle Age,449

In [50]:
df=df.drop(columns={'Total Purchase Amount'})

In [51]:
df=df.rename(columns={
    'check total':'Total Price'
})

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Customer ID       250000 non-null  object
 1   Purchase Date     250000 non-null  datetime64[ns]
 2   Product Category  250000 non-null  object
 3   Product Price     250000 non-null  int64
 4   Quantity          250000 non-null  int64
 5   Payment Method    250000 non-null  object
 6   Customer Age      250000 non-null  int64
 7   Returns           250000 non-null  int64
 8   Customer Name     250000 non-null  object
 9   Gender            250000 non-null  object
 10  Churn             250000 non-null  int64
 11  Age Category      250000 non-null  object
 12  Total Price       250000 non-null  int64
dtypes: datetime64[ns](1), int64(6), object(6)
memory usage: 24.8+ MB

In [53]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Payment Method,Customer Age,Returns,Customer Name,Gender,Churn,Age Category,Total Price
0,46251,2020-09-08 09:38:32,Electronics,12,3,Credit Card,37,0,Christine Hernandez,Male,0,Middle Age,36
1,46251,2022-03-05 12:56:35,Home,468,4,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,1872
2,46251,2022-05-23 18:18:01,Home,288,2,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,576
3,46251,2020-11-12 13:13:29,Clothing,196,1,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,196
4,13593,2020-11-27 17:55:11,Home,449,1,Credit Card,49,0,James Grant,Female,1,Middle Age,449

In [54]:
df['Customer ID'].unique()

array([46251, 13593, 28805, ..., 21019, 49234, 16971],
      shape=(49673,), dtype=object)

In [55]:
df['Customer ID'].shape

(250000,)

In [56]:
df['Customer ID'].nunique()

49673

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Customer ID       250000 non-null  object
 1   Purchase Date     250000 non-null  datetime64[ns]
 2   Product Category  250000 non-null  object
 3   Product Price     250000 non-null  int64
 4   Quantity          250000 non-null  int64
 5   Payment Method    250000 non-null  object
 6   Customer Age      250000 non-null  int64
 7   Returns           250000 non-null  int64
 8   Customer Name     250000 non-null  object
 9   Gender            250000 non-null  object
 10  Churn             250000 non-null  int64
 11  Age Category      250000 non-null  object
 12  Total Price       250000 non-null  int64
dtypes: datetime64[ns](1), int64(6), object(6)
memory usage: 24.8+ MB

In [58]:
df['Customer Total Spend'] = df.groupby('Customer ID')['Total Price'].transform('sum')

In [59]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Payment Method,Customer Age,Returns,Customer Name,Gender,Churn,Age Category,Total Price,Customer Total Spend
0,46251,2020-09-08 09:38:32,Electronics,12,3,Credit Card,37,0,Christine Hernandez,Male,0,Middle Age,36,2680
1,46251,2022-03-05 12:56:35,Home,468,4,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,1872,2680
2,46251,2022-05-23 18:18:01,Home,288,2,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,576,2680
3,46251,2020-11-12 13:13:29,Clothing,196,1,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,196,2680
4,13593,2020-11-27 17:55:11,Home,449,1,Credit Card,49,0,James Grant,Female,1,Middle Age,449,2560

In [60]:
df[['Customer ID','Churn']].tail()

       Customer ID  Churn
249995       33308      1
249996       48835      1
249997       21019      0
249998       49234      1
249999       16971      1

In [61]:
df.groupby('Customer ID')['Churn'].nunique().value_counts()

Churn
1    49673
Name: count, dtype: int64

In [62]:
df.groupby('Customer ID')['Customer Age'].nunique().max()

1

In [63]:
df.groupby('Customer ID')['Customer Name'].nunique().max()

1

In [64]:
df.groupby('Customer ID')['Product Category'].nunique().max()

4

In [65]:
df.groupby('Customer ID')['Gender'].nunique().max()

1

In [66]:
df.groupby('Customer ID')['Payment Method'].nunique().max()

4

In [67]:
df.groupby('Customer ID')['Returns'].nunique().value_counts()

Returns
2    41083
1     8590
Name: count, dtype: int64

In [87]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Payment Method,Customer Age,Returns,Customer Name,Gender,Churn,Age Category,Total Price,Customer Total Spend
0,46251,2020-09-08 09:38:32,Electronics,12,3,Credit Card,37,0,Christine Hernandez,Male,0,Middle Age,36,2680
1,46251,2022-03-05 12:56:35,Home,468,4,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,1872,2680
2,46251,2022-05-23 18:18:01,Home,288,2,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,576,2680
3,46251,2020-11-12 13:13:29,Clothing,196,1,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,196,2680
4,13593,2020-11-27 17:55:11,Home,449,1,Credit Card,49,0,James Grant,Female,1,Middle Age,449,2560

In [88]:
df=df.drop(columns={'Customer Total Spend'})

In [89]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Payment Method,Customer Age,Returns,Customer Name,Gender,Churn,Age Category,Total Price
0,46251,2020-09-08 09:38:32,Electronics,12,3,Credit Card,37,0,Christine Hernandez,Male,0,Middle Age,36
1,46251,2022-03-05 12:56:35,Home,468,4,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,1872
2,46251,2022-05-23 18:18:01,Home,288,2,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,576
3,46251,2020-11-12 13:13:29,Clothing,196,1,PayPal,37,0,Christine Hernandez,Male,0,Middle Age,196
4,13593,2020-11-27 17:55:11,Home,449,1,Credit Card,49,0,James Grant,Female,1,Middle Age,449

In [70]:
customer_table=df.groupby('Customer ID').agg(
    customer_name=('Customer Name','first'),
    age=('Customer Age','first'),
    gender=('Gender','first'),
    age_category=('Age Category','first'),
    churn=('Churn','first'),
    total_spend=('Total Price','sum'),
    average_spend=('Total Price','mean'),
    purchase_count=('Customer ID','count')
).reset_index()

In [71]:
customer_table.head()

,Customer ID,customer_name,age,gender,age_category,churn,total_spend,average_spend,purchase_count
0,1,Nicole Johnson,70,Male,Senior,0,845,845.000000,1
1,2,Marie Wright,27,Female,Adult,0,1070,356.666667,3
2,3,Julie Wolfe,23,Female,Young Adult,0,5041,630.125000,8
3,4,Tracey Smith,66,Male,Senior,1,1433,358.250000,4
4,5,Nancy Jones,26,Female,Adult,0,7881,985.125000,8

In [72]:
customer_table.shape

(49673, 9)

In [74]:
customer_table['Customer ID'].nunique()

49673

In [78]:
customer_table.iloc[49645]

Customer ID               49973
customer_name     Joseph Miller
age                          50
gender                     Male
age_category         Middle Age
churn                         0
total_spend                7457
average_spend       1065.285714
purchase_count                7
Name: 49645, dtype: object

In [80]:
customer_table.columns=customer_table.columns.str.lower()

In [81]:
customer_table.columns

Index(['customer id', 'customer_name', 'age', 'gender', 'age_category',
       'churn', 'total_spend', 'average_spend', 'purchase_count'],
      dtype='object')

In [82]:
len(customer_table)

49673

In [83]:
len(df)

250000

In [84]:
customer_table.duplicated().sum()

np.int64(0)

In [85]:
customer_table.isnull().sum()

customer id       0
customer_name     0
age               0
gender            0
age_category      0
churn             0
total_spend       0
average_spend     0
purchase_count    0
dtype: int64

In [90]:
df.columns

Index(['Customer ID', 'Purchase Date', 'Product Category', 'Product Price',
       'Quantity', 'Payment Method', 'Customer Age', 'Returns',
       'Customer Name', 'Gender', 'Churn', 'Age Category', 'Total Price'],
      dtype='object')

In [91]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.columns

Index(['customer_id', 'purchase_date', 'product_category', 'product_price',
       'quantity', 'payment_method', 'customer_age', 'returns',
       'customer_name', 'gender', 'churn', 'age_category', 'total_price'],
      dtype='object')

In [92]:
df.to_csv('transactions.csv',index=False)

In [93]:
customer_table.to_csv('customer_table.csv',index=False)